import { AddressMode, Instruction } from "./types";

const opCodes: Record<number, Instruction> = {
  0x69: {
    name: "ADC",
    addressMode: AddressMode.Immediate,
    bytes: 2,
    cycles: 2,
  },
  0x65: {
    name: "ADC",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0x75: {
    name: "ADC",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 4,
  },
  0x6d: {
    name: "ADC",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0x7d: {
    name: "ADC",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 4,
  },
  0x79: {
    name: "ADC",
    addressMode: AddressMode.AbsoluteY,
    bytes: 3,
    cycles: 4,
  },
  0x61: {
    name: "ADC",
    addressMode: AddressMode.IndexedIndirect,
    bytes: 2,
    cycles: 6,
  },
  0x71: {
    name: "ADC",
    addressMode: AddressMode.IndirectIndexed,
    bytes: 2,
    cycles: 5,
  },
  0x29: {
    name: "AND",
    addressMode: AddressMode.Immediate,
    bytes: 2,
    cycles: 2,
  },
  0x25: {
    name: "AND",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0x35: {
    name: "AND",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 4,
  },
  0x2d: {
    name: "AND",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0x3d: {
    name: "AND",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 4,
  },
  0x39: {
    name: "AND",
    addressMode: AddressMode.AbsoluteY,
    bytes: 3,
    cycles: 4,
  },
  0x21: {
    name: "AND",
    addressMode: AddressMode.IndexedIndirect,
    bytes: 2,
    cycles: 6,
  },
  0x31: {
    name: "AND",
    addressMode: AddressMode.IndirectIndexed,
    bytes: 2,
    cycles: 5,
  },
  0x0a: {
    name: "ASL",
    addressMode: AddressMode.Accumulator,
    bytes: 1,
    cycles: 2,
  },
  0x06: {
    name: "ASL",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 5,
  },
  0x16: {
    name: "ASL",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 6,
  },
  0x0e: {
    name: "ASL",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 6,
  },
  0x1e: {
    name: "ASL",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 7,
  },
  0x90: {
    name: "BCC",
    addressMode: AddressMode.Relative,
    bytes: 2,
    cycles: 2,
  },
  0xb0: {
    name: "BCS",
    addressMode: AddressMode.Relative,
    bytes: 2,
    cycles: 2,
  },
  0xf0: {
    name: "BEQ",
    addressMode: AddressMode.Relative,
    bytes: 2,
    cycles: 2,
  },
  0x24: {
    name: "BIT",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0x2c: {
    name: "BIT",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0x30: {
    name: "BMI",
    addressMode: AddressMode.Relative,
    bytes: 2,
    cycles: 2,
  },
  0xd0: {
    name: "BNE",
    addressMode: AddressMode.Relative,
    bytes: 2,
    cycles: 2,
  },
  0x10: {
    name: "BPL",
    addressMode: AddressMode.Relative,
    bytes: 2,
    cycles: 2,
  },
  0x00: {
    name: "BRK",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 7,
  },
  0x50: {
    name: "BVC",
    addressMode: AddressMode.Relative,
    bytes: 2,
    cycles: 2,
  },
  0x70: {
    name: "BVS",
    addressMode: AddressMode.Relative,
    bytes: 2,
    cycles: 2,
  },
  0x18: {
    name: "CLC",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0xd8: {
    name: "CLD",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0x58: {
    name: "CLI",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0xb8: {
    name: "CLV",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0xc9: {
    name: "CMP",
    addressMode: AddressMode.Immediate,
    bytes: 2,
    cycles: 2,
  },
  0xc5: {
    name: "CMP",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0xd5: {
    name: "CMP",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 4,
  },
  0xcd: {
    name: "CMP",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0xdd: {
    name: "CMP",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 4,
  },
  0xd9: {
    name: "CMP",
    addressMode: AddressMode.AbsoluteY,
    bytes: 3,
    cycles: 4,
  },
  0xc1: {
    name: "CMP",
    addressMode: AddressMode.IndexedIndirect,
    bytes: 2,
    cycles: 6,
  },
  0xd1: {
    name: "CMP",
    addressMode: AddressMode.IndirectIndexed,
    bytes: 2,
    cycles: 5,
  },
  0xe0: {
    name: "CPX",
    addressMode: AddressMode.Immediate,
    bytes: 2,
    cycles: 2,
  },
  0xe4: {
    name: "CPX",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0xec: {
    name: "CPX",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0xc0: {
    name: "CPY",
    addressMode: AddressMode.Immediate,
    bytes: 2,
    cycles: 2,
  },
  0xc4: {
    name: "CPY",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0xcc: {
    name: "CPY",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0xc6: {
    name: "DEC",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 5,
  },
  0xd6: {
    name: "DEC",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 6,
  },
  0xce: {
    name: "DEC",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 6,
  },
  0xde: {
    name: "DEC",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 7,
  },
  0xca: {
    name: "DEX",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0x88: {
    name: "DEY",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0x49: {
    name: "EOR",
    addressMode: AddressMode.Immediate,
    bytes: 2,
    cycles: 2,
  },
  0x45: {
    name: "EOR",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0x55: {
    name: "EOR",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 4,
  },
  0x4d: {
    name: "EOR",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0x5d: {
    name: "EOR",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 4,
  },
  0x59: {
    name: "EOR",
    addressMode: AddressMode.AbsoluteY,
    bytes: 3,
    cycles: 4,
  },
  0x41: {
    name: "EOR",
    addressMode: AddressMode.IndexedIndirect,
    bytes: 2,
    cycles: 6,
  },
  0x51: {
    name: "EOR",
    addressMode: AddressMode.IndirectIndexed,
    bytes: 2,
    cycles: 5,
  },
  0xe6: {
    name: "INC",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 5,
  },
  0xf6: {
    name: "INC",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 6,
  },
  0xee: {
    name: "INC",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 6,
  },
  0xfe: {
    name: "INC",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 7,
  },
  0xe8: {
    name: "INX",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0xc8: {
    name: "INY",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0x4c: {
    name: "JMP",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 3,
  },
  0x6c: {
    name: "JMP",
    addressMode: AddressMode.Indirect,
    bytes: 3,
    cycles: 5,
  },
  0x20: {
    name: "JSR",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 6,
  },
  0xa9: {
    name: "LDA",
    addressMode: AddressMode.Immediate,
    bytes: 2,
    cycles: 2,
  },
  0xa5: {
    name: "LDA",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0xb5: {
    name: "LDA",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 4,
  },
  0xad: {
    name: "LDA",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0xbd: {
    name: "LDA",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 4,
  },
  0xb9: {
    name: "LDA",
    addressMode: AddressMode.AbsoluteY,
    bytes: 3,
    cycles: 4,
  },
  0xa1: {
    name: "LDA",
    addressMode: AddressMode.IndexedIndirect,
    bytes: 2,
    cycles: 6,
  },
  0xb1: {
    name: "LDA",
    addressMode: AddressMode.IndirectIndexed,
    bytes: 2,
    cycles: 5,
  },
  0xa2: {
    name: "LDX",
    addressMode: AddressMode.Immediate,
    bytes: 2,
    cycles: 2,
  },
  0xa6: {
    name: "LDX",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0xb6: {
    name: "LDX",
    addressMode: AddressMode.ZeroPageY,
    bytes: 2,
    cycles: 4,
  },
  0xae: {
    name: "LDX",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0xbe: {
    name: "LDX",
    addressMode: AddressMode.AbsoluteY,
    bytes: 3,
    cycles: 4,
  },
  0xa0: {
    name: "LDY",
    addressMode: AddressMode.Immediate,
    bytes: 2,
    cycles: 2,
  },
  0xa4: {
    name: "LDY",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0xb4: {
    name: "LDY",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 4,
  },
  0xac: {
    name: "LDY",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0xbc: {
    name: "LDY",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 4,
  },
  0x4a: {
    name: "LSR",
    addressMode: AddressMode.Accumulator,
    bytes: 1,
    cycles: 2,
  },
  0x46: {
    name: "LSR",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 5,
  },
  0x56: {
    name: "LSR",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 6,
  },
  0x4e: {
    name: "LSR",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 6,
  },
  0x5e: {
    name: "LSR",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 7,
  },
  0xea: {
    name: "NOP",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0x09: {
    name: "ORA",
    addressMode: AddressMode.Immediate,
    bytes: 2,
    cycles: 2,
  },
  0x05: {
    name: "ORA",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0x15: {
    name: "ORA",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 4,
  },
  0x0d: {
    name: "ORA",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0x1d: {
    name: "ORA",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 4,
  },
  0x19: {
    name: "ORA",
    addressMode: AddressMode.AbsoluteY,
    bytes: 3,
    cycles: 4,
  },
  0x01: {
    name: "ORA",
    addressMode: AddressMode.IndexedIndirect,
    bytes: 2,
    cycles: 6,
  },
  0x11: {
    name: "ORA",
    addressMode: AddressMode.IndirectIndexed,
    bytes: 2,
    cycles: 5,
  },
  0x48: {
    name: "PHA",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 3,
  },
  0x08: {
    name: "PHP",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 3,
  },
  0x68: {
    name: "PLA",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 4,
  },
  0x28: {
    name: "PLP",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 4,
  },
  0x2a: {
    name: "ROL",
    addressMode: AddressMode.Accumulator,
    bytes: 1,
    cycles: 2,
  },
  0x26: {
    name: "ROL",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 5,
  },
  0x36: {
    name: "ROL",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 6,
  },
  0x2e: {
    name: "ROL",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 6,
  },
  0x3e: {
    name: "ROL",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 7,
  },
  0x6a: {
    name: "ROR",
    addressMode: AddressMode.Accumulator,
    bytes: 1,
    cycles: 2,
  },
  0x66: {
    name: "ROR",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 5,
  },
  0x76: {
    name: "ROR",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 6,
  },
  0x6e: {
    name: "ROR",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 6,
  },
  0x7e: {
    name: "ROR",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 7,
  },
  0x40: {
    name: "RTI",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 6,
  },
  0x60: {
    name: "RTS",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 6,
  },
  0xe9: {
    name: "SBC",
    addressMode: AddressMode.Immediate,
    bytes: 2,
    cycles: 2,
  },
  0xe5: {
    name: "SBC",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0xf5: {
    name: "SBC",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 4,
  },
  0xed: {
    name: "SBC",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0xfd: {
    name: "SBC",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 4,
  },
  0xf9: {
    name: "SBC",
    addressMode: AddressMode.AbsoluteY,
    bytes: 3,
    cycles: 4,
  },
  0xe1: {
    name: "SBC",
    addressMode: AddressMode.IndexedIndirect,
    bytes: 2,
    cycles: 6,
  },
  0xf1: {
    name: "SBC",
    addressMode: AddressMode.IndirectIndexed,
    bytes: 2,
    cycles: 5,
  },
  0x38: {
    name: "SEC",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0xf8: {
    name: "SED",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0x78: {
    name: "SEI",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0x85: {
    name: "STA",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0x95: {
    name: "STA",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 4,
  },
  0x8d: {
    name: "STA",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0x9d: {
    name: "STA",
    addressMode: AddressMode.AbsoluteX,
    bytes: 3,
    cycles: 5,
  },
  0x99: {
    name: "STA",
    addressMode: AddressMode.AbsoluteY,
    bytes: 3,
    cycles: 5,
  },
  0x81: {
    name: "STA",
    addressMode: AddressMode.IndexedIndirect,
    bytes: 2,
    cycles: 6,
  },
  0x91: {
    name: "STA",
    addressMode: AddressMode.IndirectIndexed,
    bytes: 2,
    cycles: 6,
  },
  0x86: {
    name: "STX",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0x96: {
    name: "STX",
    addressMode: AddressMode.ZeroPageY,
    bytes: 2,
    cycles: 4,
  },
  0x8e: {
    name: "STX",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0x84: {
    name: "STY",
    addressMode: AddressMode.ZeroPage,
    bytes: 2,
    cycles: 3,
  },
  0x94: {
    name: "STY",
    addressMode: AddressMode.ZeroPageX,
    bytes: 2,
    cycles: 4,
  },
  0x8c: {
    name: "STY",
    addressMode: AddressMode.Absolute,
    bytes: 3,
    cycles: 4,
  },
  0xaa: {
    name: "TAX",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0xa8: {
    name: "TAY",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0xba: {
    name: "TSX",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0x8a: {
    name: "TXA",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0x9a: {
    name: "TXS",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
  0x98: {
    name: "TYA",
    addressMode: AddressMode.Implicit,
    bytes: 1,
    cycles: 2,
  },
};

export default opCodes;
export type { Instruction };